name: Build & Release Extension

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP extension archive
        run: |
          zip -r faceitbetter-${{ github.ref_name }}.zip icons src manifest.json

      - name: Upload ZIP to Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: faceitbetter-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}